#!/usr/bin/env ts-node
/**
 * Report Generator
 * 
 * Creates pre-meeting discovery reports
 * SCRIBE coordination for formatting
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { Skill, DiscoveryReport } from './types';

export class ReportGenerator {
  async generate(skills: Skill[]): Promise<string> {
    const date = new Date().toISOString().split('T')[0];
    
    // Group by priority
    const highPriority = skills.filter(s => s.complexity === 'expert' || (s.usageCount && s.usageCount >= 5));
    const mediumPriority = skills.filter(s => !highPriority.includes(s) && s.complexity !== 'simple');
    const lowPriority = skills.filter(s => !highPriority.includes(s) && !mediumPriority.includes(s));
    
    // Generate markdown
    const markdown = `# 🔍 Skills Discovery Report

**Date**: ${date}  
**Period**: Last 48 hours  
**New Skills**: ${skills.length} discovered  
**Status**: Pending review

---

## 🆕 NEW SKILLS DISCOVERED

### HIGH PRIORITY (${highPriority.length})

${this.formatSkills(highPriority, true)}

### MEDIUM PRIORITY (${mediumPriority.length})

${this.formatSkills(mediumPriority, false)}

### LOW PRIORITY (${lowPriority.length})

${this.formatSkills(lowPriority, false)}

---

## 📊 DISCOVERY STATISTICS

| Metric | Value |
|--------|-------|
| Total Skills | ${skills.length} |
| High Priority | ${highPriority.length} |
| Medium Priority | ${mediumPriority.length} |
| Low Priority | ${lowPriority.length} |
| Constitutional Passes | ${skills.filter(s => s.constitutionalCompliance.validated).length} |

---

## 🎯 RECOMMENDATIONS

### Immediate Actions:
1. ✅ Review HIGH priority skills (${highPriority.length} skills)
2. 📚 Add to skills library documentation
3. 🔄 Update agent capability matrices

### This Week:
4. 🔨 Implement MEDIUM priority skills
5. 🧪 Test in sandbox environment

---

## 💬 ACTIONS

Say **"approve all"** to add HIGH priority skills immediately  
Say **"review [number]"** to examine a specific skill  
Say **"defer [number]"** to postpone a skill  

---

**Generated by**: Skills Discovery System v1.0  
**Next Discovery**: ${this.getNextDiscoveryDate()}  
**Agent Coordination**: KEEPER + ARCH + LEX + VERA
`;
    
    // Save report
    await this.save(markdown, date);
    
    // Output summary for GitHub Actions
    console.log(`::set-output name=summary::${skills.length} skills discovered`);
    
    return markdown;
  }
  
  private formatSkills(skills: Skill[], detailed: boolean): string {
    if (skills.length === 0) return 'None\n';
    
    return skills.map((skill, i) => {
      let output = `#### ${i + 1}. **${skill.name}**\n`;
      output += `- **Agent**: ${skill.agents.join(', ') || 'Unassigned'}\n`;
      output += `- **Category**: ${skill.category}\n`;
      output += `- **Description**: ${skill.description}\n`;
      
      if (detailed) {
        output += `- **Source**: ${skill.source.type}${skill.source.url ? ` - [Link](${skill.source.url})` : ''}\n`;
        output += `- **Complexity**: ${skill.complexity}\n`;
        if (skill.usageCount) {
          output += `- **Usage**: ${skill.usageCount} times\n`;
        }
      }
      
      output += '\n';
      return output;
    }).join('');
  }
  
  private getNextDiscoveryDate(): string {
    const next = new Date();
    next.setHours(next.getHours() + 48);
    return next.toISOString().split('T')[0];
  }
  
  private async save(markdown: string, date: string): Promise<void> {
    const reportDir = path.join(
      process.cwd(),
      'SESSION_LOGS/SKILLS_DISCOVERY_REPORTS'
    );
    
    await fs.mkdir(reportDir, { recursive: true });
    
    // Save dated report
    await fs.writeFile(
      path.join(reportDir, `${date}.md`),
      markdown
    );
    
    // Save as latest
    await fs.writeFile(
      path.join(reportDir, 'latest.md'),
      markdown
    );
  }
}

// Run if called directly
if (require.main === module) {
  (async () => {
    // Load discovered skills from latest run
    const fs = require('fs').promises;
    const path = require('path');
    const glob = require('glob');
    
    const files = glob.sync('agents/skills-library/auto-discovered/*.json');
    if (files.length === 0) {
      console.log('No discovered skills found');
      process.exit(0);
    }
    
    // Load most recent
    const latest = files.sort().pop();
    const content = JSON.parse(await fs.readFile(latest, 'utf-8'));
    
    const generator = new ReportGenerator();
    await generator.generate(content.skills);
    
    console.log('✅ Report generated');
  })();
}
