/**
 * Zero-Day GTM Funnel — PostHog event library
 * Tracks the client intake → contract → delivery pipeline.
 */

declare const window: any;
declare function require(module: string): { default: unknown };

let ph: { capture: (event: string, props?: Record<string, unknown>) => void } | null = null;

function getPostHog() {
  if (ph) return ph;
  if (typeof window !== 'undefined') {
    // Lazy-load to avoid SSR issues
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      // @ts-ignore
      const { posthog } = require('posthog-js') as { posthog: typeof ph };
      ph = posthog;
    } catch {
      ph = { capture: () => undefined };
    }
  }
  return ph ?? { capture: () => undefined };
}

/** Client opens the intake session */
export function trackIntakeStarted(clientEmail: string, projectType?: string): void {
  getPostHog()?.capture('intake_started', {
    client_email_domain: clientEmail.split('@')[1],
    project_type: projectType,
    timestamp: new Date().toISOString(),
  });
}

/** Client completes a question step */
export function trackIntakeStep(step: number, questionType: string): void {
  getPostHog()?.capture('intake_step_completed', {
    step,
    question_type: questionType,
    timestamp: new Date().toISOString(),
  });
}

/** Brief generated from intake */
export function trackBriefGenerated(projectType: string, budgetRange: string, confidenceScore: number): void {
  getPostHog()?.capture('brief_generated', {
    project_type: projectType,
    budget_range: budgetRange,
    confidence_score: confidenceScore,
    timestamp: new Date().toISOString(),
  });
}

/** Contract generated by LEX */
export function trackContractGenerated(contractType: string, estimatedValue?: number): void {
  getPostHog()?.capture('contract_generated', {
    contract_type: contractType,
    estimated_value: estimatedValue,
    timestamp: new Date().toISOString(),
  });
}

/** Contract previewed by human before send */
export function trackContractPreviewed(): void {
  getPostHog()?.capture('contract_previewed', { timestamp: new Date().toISOString() });
}

/** Contract sent to client */
export function trackContractSent(recipientDomain: string): void {
  getPostHog()?.capture('contract_sent', {
    recipient_domain: recipientDomain,
    timestamp: new Date().toISOString(),
  });
}

/** Client signed/accepted the contract */
export function trackContractSigned(value?: number): void {
  getPostHog()?.capture('contract_signed', {
    value,
    timestamp: new Date().toISOString(),
  });
}
