#!/usr/bin/env python3
"""
Sovereign Academy - Udemy Transcript Harvester
==============================================
Fully autonomous OTP-integrated Udemy harvester.
Restored for V6 to process curriculum JSONs and extract transcripts 
via automated Playwright browsing and IMAP OTP polling.
"""

import asyncio
import os
import json
import time
import re
import requests
import imaplib
import email
from email.header import decode_header
from datetime import datetime, timezone
from playwright.async_api import async_playwright, Page

CORTEX_EMAIL = "inquiries@creativeliberationengine.org"
CORTEX_PASS = os.getenv("CORTEX_PASSWORD", "WholeTroutMedia!2026")

NAS_RAG_DATA = r"\\127.0.0.1\docker\genesis-deploy\media_intake\Resolve_RAG_Data\Learning"
NAS_AUTH_DATA = r"\\127.0.0.1\docker\genesis-deploy\media_intake\Resolve_RAG_Data\Auth"
DISPATCH_URL = "http://127.0.0.1:5160/api/tasks"

# Curriculums generated by standard scraper
CURRICULUM_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "knowledge-ingestion", "udemy")

def get_udemy_otp(retries=12, delay=10):
    """Polls Gmail via IMAP for the Udemy OTP code."""
    print(f"[*] Polling email ({CORTEX_EMAIL}) for Udemy OTP via IMAP...")
    for i in range(retries):
        try:
            mail = imaplib.IMAP4_SSL('imap.gmail.com')
            mail.login(CORTEX_EMAIL, CORTEX_PASS)
            mail.select('inbox')
            
            # Search for unseen emails
            status, messages = mail.search(None, '(UNSEEN FROM "udemy")')
            if status == 'OK' and messages[0]:
                for num in messages[0].split():
                    res, msg_data = mail.fetch(num, '(RFC822)')
                    for response_part in msg_data:
                        if isinstance(response_part, tuple):
                            msg = email.message_from_bytes(response_part[1])
                            
                            # Parse body
                            body = ""
                            if msg.is_multipart():
                                for part in msg.walk():
                                    if part.get_content_type() == "text/plain":
                                        body = part.get_payload(decode=True).decode()
                                        break
                            else:
                                body = msg.get_payload(decode=True).decode()
                            
                            # Match 6-digit code typical of Udemy
                            match = re.search(r'\b(\d{6})\b', body)
                            if match:
                                code = match.group(1)
                                print(f"  [+] Found Udemy OTP: {code}")
                                mail.close()
                                mail.logout()
                                return code
            mail.close()
            mail.logout()
        except Exception as e:
            print(f"  [!] IMAP Error: {e}")
            print(f"      (If auth fails, ensure an App Password is used or IMAP is enabled in Workspace)")
        
        print(f"  [~] No OTP found yet. Waiting {delay} seconds... ({i+1}/{retries})")
        time.sleep(delay)
    
    print("  [!] Failed to retrieve OTP within the timeframe.")
    return None

def dispatch_ingestion_task(course_name: str, file_path: str):
    task_payload = {
        "queue": "cortex_learning",
        "type": "udemy_transcript_ingest",
        "priority": "high",
        "status": "pending",
        "payload": {
            "platform": "Udemy",
            "course": course_name,
            "rag_path": file_path,
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
    }
    try:
        resp = requests.post(DISPATCH_URL, json=task_payload, timeout=5)
        if resp.status_code in (200, 201):
            print(f"  [+] Dispatch successful: {resp.json().get('id', 'unknown')}")
        else:
            print(f"  [!] Dispatch failed: {resp.status_code}")
    except Exception as e:
        print(f"  [!] Dispatch error: {e}")

async def harvest_transcripts():
    print("="*60)
    print("  UDEMY TRANSCRIPT HARVESTER (AUTONOMOUS OTP)")
    print("="*60)
    
    profile_dir = os.path.join(NAS_AUTH_DATA, "udemy_chrome_profile")
    os.makedirs(profile_dir, exist_ok=True)
    os.makedirs(NAS_RAG_DATA, exist_ok=True)
    
    async with async_playwright() as p:
        print("  [*] Connecting to CORTEX Browser via CDP...")
        try:
            browser = await p.chromium.connect_over_cdp("http://127.0.0.1:9224")
            context = browser.contexts[0]
            context.set_default_timeout(60000)
            page = context.pages[0] if context.pages else await context.new_page()
        except Exception as e:
            print(f"  [!] Failed to connect to CDP: {e}")
            return
            
        print("[*] Checking Udemy authentication status...")
        await page.goto("https://www.udemy.com/join/login-popup/", wait_until="domcontentloaded")
        await page.wait_for_timeout(4000)
        
        # Check if login fields are present
        if await page.locator("input[name='email']").count() > 0:
            print("[*] User not logged in. Initiating login flow...")
            await page.fill("input[name='email']", CORTEX_EMAIL)
            
            # Click the main continue/submit button
            submit_btn = page.locator("button[type='submit']")
            if await submit_btn.count() > 0:
                await submit_btn.first.click()
                await page.wait_for_timeout(4000)
            
            # Check if password is requested
            pw_loc = page.locator("input[name='password']")
            if await pw_loc.count() > 0:
                print("  [*] Password requested.")
                await pw_loc.first.fill(CORTEX_PASS)
                await page.locator("button[type='submit']").first.click()
                await page.wait_for_timeout(5000)
            
            # Check for OTP inputs (either 'code', 'otp', or 6 distinct boxes)
            otp_loc = page.locator("input[name*='code'], input[name*='otp'], input[maxlength='6']")
            if await otp_loc.count() > 0:
                print("  [*] Udemy requested 2FA/OTP code.")
                otp = get_udemy_otp()
                if otp:
                    print(f"  [*] Filling OTP: {otp}")
                    count = await otp_loc.count()
                    if count == 6:
                        # 6 separate boxes
                        for idx, char in enumerate(otp):
                            await otp_loc.nth(idx).fill(char)
                    else:
                        # Single input field
                        await otp_loc.first.fill(otp)
                    
                    submit_btn = page.locator("button[type='submit'], button:has-text('Verify')")
                    if await submit_btn.count() > 0:
                        await submit_btn.first.click()
                    await page.wait_for_timeout(8000)
                else:
                    print("  [!] Cannot proceed without OTP. Exiting.")
                    await page.close()
                    await browser.close()
                    return
        
        # Verify dashboard access
        await page.goto("https://www.udemy.com/home/my-courses/learning/", wait_until="domcontentloaded")
        await page.wait_for_timeout(5000)
        if await page.locator("a[data-purpose='user-dropdown'], div[data-purpose='my-learning-courses']").count() > 0:
            print("[+] Successfully authenticated to Udemy.")
        else:
            print("[!] Authentication seems to have failed or page layout changed.")
            # We don't exit immediately in case the selector is just wrong, but we log it.
            
        print("[*] Locating syllabus files...")
        if not os.path.exists(CURRICULUM_DIR):
            print(f"[!] Curriculum directory not found at {CURRICULUM_DIR}.")
            await page.close()
            await browser.close()
            return
            
        processed_count = 0
        for d in os.listdir(CURRICULUM_DIR):
            course_dir = os.path.join(CURRICULUM_DIR, d)
            if not os.path.isdir(course_dir): continue
            
            syllabus_file = os.path.join(course_dir, "syllabus.md")
            if not os.path.exists(syllabus_file): continue
            
            try:
                with open(syllabus_file, "r", encoding="utf-8") as f:
                    syllabus_content = f.read()
            except Exception as e:
                print(f"  [!] Failed to read {syllabus_file}: {e}")
                continue
                
            # Extract course URL
            match = re.search(r'\*\*Source:\*\* \[.*?\]\((https://www\.udemy\.com/course/.*?/)\)', syllabus_content)
            if not match:
                print(f"  [!] Could not find course URL in {syllabus_file}")
                continue
                
            base_url = match.group(1)
            learning_url = f"{base_url.rstrip('/')}/learn/"
            
            # Extract title (first line starting with # )
            title_match = re.search(r'^#\s+(.*)', syllabus_content, re.MULTILINE)
            course_title = title_match.group(1).strip() if title_match else d
            print(f"\n[*] Processing Course: {course_title}")
            print(f"  [>] Navigating to: {learning_url}")
            
            try:
                await page.goto(learning_url, wait_until="domcontentloaded")
                await page.wait_for_timeout(8000)
                
                # Autonomous crawl logic within the course
                max_lectures = 200
                consecutive_fails = 0
                
                for i in range(max_lectures):
                    # Check for transcript
                    transcript_btn = page.locator("button[data-purpose='transcript-toggle'], button[aria-label*='Transcript'], div[data-purpose='transcript-toggle']")
                    if await transcript_btn.count() > 0:
                        if not await page.locator("div[data-purpose='transcript-panel']").is_visible():
                            try:
                                await transcript_btn.first.click(timeout=3000)
                                await page.wait_for_timeout(2000)
                            except:
                                pass
                                
                    transcript_loc = page.locator("div[data-purpose='transcript-panel']")
                    
                    # We need the current lecture title to save the file
                    # Usually in header or below video
                    title_loc = page.locator("h1, h2[data-purpose='learning-object-title']")
                    current_title = f"lecture_{i}"
                    if await title_loc.count() > 0:
                        current_title = await title_loc.first.inner_text()
                    
                    safe_title = re.sub(r'[^a-zA-Z0-9_\-]', '_', current_title.strip())
                    dest_file = os.path.join(NAS_RAG_DATA, f"udemy_{d}_{i:03d}_{safe_title}.txt")
                    
                    if await transcript_loc.count() > 0:
                        text = await transcript_loc.inner_text()
                        if text and len(text.strip()) > 50:
                            if not os.path.exists(dest_file):
                                with open(dest_file, "w", encoding="utf-8") as out_f:
                                    out_f.write(text)
                                print(f"  [+] Saved transcript: {dest_file}")
                                dispatch_ingestion_task(course_title, dest_file)
                                processed_count += 1
                                consecutive_fails = 0
                            else:
                                print(f"      Already harvested {current_title}. Skipping.")
                                consecutive_fails = 0
                        else:
                            print(f"  [-] Transcript empty for {current_title}.")
                            consecutive_fails += 1
                    else:
                        print(f"  [-] No transcript panel for {current_title}.")
                        consecutive_fails += 1
                        
                    if consecutive_fails > 10:
                        print("  [!] Too many consecutive missing transcripts, might be end of course or stuck. Breaking.")
                        break

                    # Click next
                    next_selectors = [
                        "div[data-purpose='go-to-next-button']",
                        "button[data-purpose='go-to-next-button']",
                        "div[aria-label='Go to next item']",
                        "button[aria-label='Go to next item']",
                        "div[data-purpose='next-item']",
                        "div.next-and-previous--button-container--1g-dG:has-text('Next')"
                    ]
                    clicked = False
                    for sel in next_selectors:
                        try:
                            loc = page.locator(sel)
                            if await loc.count() > 0 and await loc.is_visible(timeout=1000):
                                print(f"  [>] Clicking Next...")
                                await loc.first.click(timeout=3000)
                                clicked = True
                                await page.wait_for_timeout(6000)
                                break
                        except:
                            pass
                            
                    if not clicked:
                        print("  [!] Could not find 'Next' button. Course likely finished.")
                        break
                        
            except Exception as e:
                print(f"  [!] Failed to process course {course_title}: {e}")
        
        print(f"\n[+] Harvest complete. {processed_count} transcripts extracted.")
        await page.close()
        await browser.close()

if __name__ == "__main__":
    asyncio.run(harvest_transcripts())
