name: Get Tunnel URL
on: [push]
jobs:
  get-url:
    runs-on: host
    env:
      DOCKER_HOST: "unix:///var/run/docker.sock"
    steps:
      - name: Fetch URL
        run: docker logs cloudflared-tunnel 2>&1 | grep trycloudflare.com | tail -n 1 || true

