"""Ollama Adapter

Generates Ollama Modelfile for local model deployment.

Created: 2026-02-14
Author: RELAY (local protocols)
"""

from pathlib import Path
from typing import Dict, Any
from .base_adapter import BaseAdapter


class OllamaAdapter(BaseAdapter):
    """Adapter for Ollama local models."""
    
    def generate_config(self, project_path: Path, project_dna: Dict[str, Any]) -> Dict[str, Any]:
        """Generate Ollama configuration."""
        adapter_path = project_path / ".adapters" / "ollama"
        adapter_path.mkdir(parents=True, exist_ok=True)
        
        # Generate Modelfile
        modelfile_path = adapter_path / "Modelfile"
        with open(modelfile_path, "w") as f:
            f.write(self._generate_modelfile(project_dna))
        
        # Generate context file
        context_path = adapter_path / "context.txt"
        with open(context_path, "w") as f:
            f.write(self._generate_context(project_dna))
        
        # Generate README
        readme_path = adapter_path / "README.md"
        with open(readme_path, "w") as f:
            f.write(self._generate_readme())
        
        return {
            "platform": "ollama",
            "files_generated": [
                str(modelfile_path),
                str(context_path),
                str(readme_path),
            ],
            "local_deployment": True,
        }
    
    def validate_compatibility(self, project_dna: Dict[str, Any]) -> Dict[str, Any]:
        """Validate Ollama compatibility."""
        return {
            "compatible": True,
            "local_only": True,
            "recommendations": ["Install Ollama from ollama.ai"],
        }
    
    def _generate_modelfile(self, project_dna: Dict) -> str:
        """Generate Ollama Modelfile."""
        project_name = project_dna.get("name", "project")
        constitution = project_dna.get("strategic_dna", {}).get("economics", {})
        
        return f"""# Modelfile for {project_name}
# Generated by Creative Liberation Engine

FROM llama2

# System prompt with project DNA
SYSTEM """
You are an AI assistant for the {project_name} project.

This project follows Creative Liberation Engine constitutional principles:

1. Artist Revenue: {constitution.get('artist_revenue_share', '50%')} to artists always
2. Transparency: Open source, auditable code
3. Ethics: Human augmentation, not replacement
4. Sustainability: Regenerative economics

When helping with this project:
- Respect these constitutional principles
- Follow patterns in .cle/ directory
- Maintain code quality and documentation
- Suggest improvements aligned with project DNA

Project DNA available in .cle/manifest.json
"""

# Parameters
PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER top_k 40
"""
    
    def _generate_context(self, project_dna: Dict) -> str:
        """Generate context file for Ollama."""
        import json
        return f"""PROJECT DNA CONTEXT

This file provides context for the Ollama model.

{json.dumps(project_dna, indent=2)}
"""
    
    def _generate_readme(self) -> str:
        """Generate Ollama README."""
        return """# Ollama Local Deployment

## Prerequisites

1. Install Ollama:
   ```bash
   # macOS
   brew install ollama
   
   # Linux
   curl -fsSL https://ollama.ai/install.sh | sh
   
   # Windows
   # Download from ollama.ai
   ```

2. Pull base model:
   ```bash
   ollama pull llama2
   ```

## Setup

1. Copy Modelfile:
   ```bash
   cp .adapters/ollama/Modelfile .
   ```

2. Create model:
   ```bash
   ollama create myproject -f Modelfile
   ```

3. Run model:
   ```bash
   ollama run myproject
   ```

## Usage

```bash
# Interactive chat
ollama run myproject

# API usage
curl http://localhost:11434/api/generate -d '{
  "model": "myproject",
  "prompt": "Help me with this project"
}'
```

## Custom Context

The model includes project DNA from `.cle/` automatically.

## Benefits

- ✅ Fully local (no API calls)
- ✅ Privacy-first
- ✅ Project-aware
- ✅ Constitutional compliance embedded
"""
    
    def get_deploy_command(self) -> str:
        return "ollama create myproject -f .adapters/ollama/Modelfile"
