"""Vertex AI Studio Adapter

Generates Google Drive sync configuration for Vertex AI Studio access.

Vertex AI Studio can read projects from Google Drive, making this adapter
essential for seamless integration.

Created: 2026-02-14
Author: RELAY (communication protocols)
"""

import json
from pathlib import Path
from typing import Dict, Any
from .base_adapter import BaseAdapter


class VertexAIAdapter(BaseAdapter):
    """Adapter for Google Vertex AI Studio."""
    
    def generate_config(self, project_path: Path, project_dna: Dict[str, Any]) -> Dict[str, Any]:
        """Generate Vertex AI Studio configuration."""
        adapter_path = project_path / ".adapters" / "vertex-ai"
        adapter_path.mkdir(parents=True, exist_ok=True)
        
        # Generate README
        readme_content = self._generate_readme(project_dna)
        readme_path = adapter_path / "README.md"
        with open(readme_path, "w") as f:
            f.write(readme_content)
        
        # Generate sync script
        sync_script = self._generate_sync_script(project_dna)
        sync_path = adapter_path / "sync-to-drive.sh"
        with open(sync_path, "w") as f:
            f.write(sync_script)
        sync_path.chmod(0o755)  # Make executable
        
        # Generate .env template
        env_template = self._generate_env_template()
        env_path = adapter_path / ".env.template"
        with open(env_path, "w") as f:
            f.write(env_template)
        
        return {
            "platform": "vertex-ai",
            "files_generated": [
                str(readme_path),
                str(sync_path),
                str(env_path),
            ],
            "requires_drive_sync": True,
        }
    
    def validate_compatibility(self, project_dna: Dict[str, Any]) -> Dict[str, Any]:
        """Validate Vertex AI compatibility."""
        warnings = []
        
        # Check for large files
        # Note: This is a placeholder - actual implementation would scan
        if project_dna.get("architecture", {}).get("pattern") == "microservices":
            warnings.append("Microservices may require multiple Drive folders")
        
        return {
            "compatible": True,
            "warnings": warnings,
            "recommendations": [
                "Install rclone for automatic sync",
                "Configure Google Drive access",
            ],
        }
    
    def _generate_readme(self, project_dna: Dict) -> str:
        """Generate Vertex AI Studio README."""
        project_name = project_dna.get("name", "project")
        
        return f"""# Vertex AI Studio Setup

## Prerequisites

1. Google Cloud account
2. Vertex AI Studio access
3. rclone installed

## Setup

### 1. Install rclone

```bash
# macOS
brew install rclone

# Linux
curl https://rclone.org/install.sh | sudo bash

# Windows
choco install rclone
```

### 2. Configure Google Drive

```bash
rclone config
# Follow prompts to add Google Drive
# Name it 'gdrive'
```

### 3. Sync Project

```bash
./sync-to-drive.sh
```

## Access in Vertex AI Studio

1. Open [Vertex AI Studio](https://console.cloud.google.com/vertex-ai/studio)
2. Navigate to your Google Drive folder
3. Open `vertex-projects/{project_name}`
4. Start building with full project context!

## Auto-Sync (Optional)

Set up automatic sync with cron:

```bash
# Edit crontab
crontab -e

# Add this line (sync every 5 minutes)
*/5 * * * * cd /path/to/{project_name} && ./.adapters/vertex-ai/sync-to-drive.sh
```

## Environment Variables

Copy `.env.template` to `.env` and fill in your values:

```bash
cp .env.template .env
# Edit .env with your credentials
```
"""
    
    def _generate_sync_script(self, project_dna: Dict) -> str:
        """Generate Google Drive sync script."""
        project_name = project_dna.get("name", "project")
        
        return f"""#!/bin/bash
# Sync project to Google Drive for Vertex AI Studio
# Generated by Creative Liberation Engine

set -e

PROJECT_NAME="{project_name}"
DRIVE_PATH="gdrive:vertex-projects/${{PROJECT_NAME}}"

echo "🚀 Syncing to Google Drive..."
echo "📁 Project: ${{PROJECT_NAME}}"

# Check if rclone is installed
if ! command -v rclone &> /dev/null; then
    echo "❌ Error: rclone not installed"
    echo "Install: https://rclone.org/install/"
    exit 1
fi

# Check if gdrive is configured
if ! rclone listremotes | grep -q "gdrive:"; then
    echo "❌ Error: Google Drive not configured"
    echo "Run: rclone config"
    exit 1
fi

# Sync to Drive
rclone sync . "${{DRIVE_PATH}}" \
  --exclude node_modules/** \
  --exclude .git/** \
  --exclude dist/** \
  --exclude build/** \
  --exclude .next/** \
  --exclude .cache/** \
  --exclude __pycache__/** \
  --exclude *.pyc \
  --exclude .env \
  --exclude .env.local \
  --progress

echo "✅ Sync complete!"
echo "📍 Location: ${{DRIVE_PATH}}"
echo "🎯 Open Vertex AI Studio to access project"
"""
    
    def _generate_env_template(self) -> str:
        """Generate environment template."""
        return """# Vertex AI Studio Environment Variables

# Google Cloud Project ID
GCP_PROJECT_ID=your-project-id

# Vertex AI Region
VERTEX_AI_REGION=us-central1

# Google Drive Folder (optional override)
# GDRIVE_FOLDER=vertex-projects
"""
    
    def get_setup_instructions(self) -> str:
        """Get setup instructions."""
        return "See .adapters/vertex-ai/README.md"
    
    def get_deploy_command(self) -> str:
        """Get deploy command."""
        return "./adapters/vertex-ai/sync-to-drive.sh"
