"""gRPC servicer stubs for cle.spatial service.

Development placeholder — real file generated by Docker build via grpc_tools.protoc.
Provides the servicer base class and server registration function.
"""
from __future__ import annotations


class SpatialIntelligenceServicer:
    """Base class for SpatialIntelligence gRPC servicer.

    Override these methods in the real servicer implementation.
    Method signatures match proto/spatial.proto service definition.
    """

    def EncodePointCloud(self, request, context):
        context.set_code(501)
        context.set_details("Not implemented")
        raise NotImplementedError("EncodePointCloud not implemented")

    def EstimateDepth(self, request, context):
        context.set_code(501)
        context.set_details("Not implemented")
        raise NotImplementedError("EstimateDepth not implemented")

    def QueryScene(self, request, context):
        context.set_code(501)
        context.set_details("Not implemented")
        raise NotImplementedError("QueryScene not implemented")

    def BuildSceneGraph(self, request, context):
        context.set_code(501)
        context.set_details("Not implemented")
        raise NotImplementedError("BuildSceneGraph not implemented")

    def StreamEncode(self, request_iterator, context):
        context.set_code(501)
        context.set_details("Not implemented")
        raise NotImplementedError("StreamEncode not implemented")


def add_SpatialIntelligenceServicer_to_server(servicer, server):
    """Register the SpatialIntelligence servicer with a gRPC server.

    In the real generated code, this wires up all RPC method handlers.
    This stub version is a no-op for development/testing.
    """
    pass  # Real implementation generated by grpc_tools.protoc


class SpatialIntelligenceStub:
    """Client stub for SpatialIntelligence gRPC service."""

    def __init__(self, channel):
        self.channel = channel
        # Real stubs generated by grpc_tools.protoc
