/**
 * Capability Manifest — typed native TypeScript export (MCP-02)
 *
 * Exports the full manifest data as a strongly-typed CapabilityManifest object.
 * Using a .ts file avoids JSON import limitations in composite tsconfig mode (TS6307).
 *
 * To update the manifest, edit this file directly. The JSON file
 * (capability-manifest.json) is kept as the source of record for external tools
 * (Claude IDE, documentation, etc) — keep both in sync manually or via script.
 */

import type { CapabilityManifest } from './types.js';

export const manifest: CapabilityManifest = {
    version: '1.0.0',
    maxActiveConcurrent: 6,
    defaultEvictionPolicy: 'lru',
    domains: {
        cloud: [
            {
                id: 'cloud-run-mcp',
                name: 'Cloud Run MCP',
                description: 'Deploy and manage Google Cloud Run services',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['cloud run', 'deploy', 'container', 'gcp', 'google cloud', 'cloud function', 'serverless', 'docker image', 'cloud build'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@google-cloud/cloud-run-mcp'],
            },
            {
                id: 'cloudrun',
                name: 'CloudRun Simple',
                description: 'Simplified Cloud Run deployment helper',
                enabled: true,
                alwaysOn: false,
                priority: 2,
                keywords: ['cloud run', 'deploy service', 'run deploy', 'list services', 'service url'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'cloudrun-mcp'],
            },
        ],
        compute: [
            {
                id: 'compute-mcp',
                name: 'Compute MCP',
                description: 'Manage Google Compute Engine VMs and resources',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['compute engine', 'vm', 'virtual machine', 'gce', 'instance', 'disk', 'snapshot', 'machine type', 'mig', 'instance group'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@google-cloud/compute-mcp'],
            },
        ],
        data: [
            {
                id: 'bigquery-mcp',
                name: 'BigQuery MCP',
                description: 'Query and manage BigQuery datasets',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['bigquery', 'bq', 'sql', 'data warehouse', 'dataset', 'table', 'query', 'analytics'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@google-cloud/bigquery-mcp'],
            },
            {
                id: 'firestore-mcp',
                name: 'Firestore MCP',
                description: 'Manage Firestore documents and collections',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['firestore', 'document', 'collection', 'nosql', 'firebase database', 'realtime'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@google-cloud/firestore-mcp'],
            },
        ],
        logging: [
            {
                id: 'cloud-logging-mcp',
                name: 'Cloud Logging MCP',
                description: 'Query and manage Google Cloud Logging',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['logs', 'logging', 'cloud logging', 'log entries', 'log bucket', 'stackdriver', 'monitoring', 'alerts'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@google-cloud/cloud-logging-mcp'],
            },
        ],
        design: [
            {
                id: 'cle-design-ingest',
                name: 'Design Ingest MCP',
                description:
                    'Multi-source pattern extraction pipeline (Framer, Mobbin, vision) — brokers design.extract_* tools for the console registry',
                enabled: true,
                alwaysOn: true,
                priority: 1,
                keywords: [
                    'design',
                    'extract',
                    'framer',
                    'mobbin',
                    'vision',
                    'reconstruct',
                    'ingest',
                    'rag',
                    'react',
                    'pattern',
                    'unframer',
                ],
                transport: 'stdio',
                command: 'pnpm',
                args: ['--filter', '@cle/design-ingest', 'exec', 'node', 'dist/mcp-server.js'],
            },
            {
                id: 'figma-dev-mode-mcp-server',
                name: 'Figma Dev Mode MCP',
                description: 'Access Figma design files, components, and assets',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['figma', 'design', 'component', 'frame', 'token', 'ui spec', 'mockup', 'wireframe', 'prototype', 'design file'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'figma-mcp'],
            },
            {
                id: 'StitchMCP',
                name: 'Stitch MCP (Google Stitch)',
                description:
                    'Google Stitch official MCP — UI screens and frontend code from prompts (see https://stitch.withgoogle.com/docs/mcp/setup). Pairs with Genkit POST /stitch in-repo.',
                enabled: true,
                alwaysOn: false,
                priority: 2,
                keywords: [
                    'stitch',
                    'google stitch',
                    'screen',
                    'generate ui',
                    'ui generation',
                    'design system',
                    'ui screen',
                    'generate screen',
                ],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'stitch-mcp'],
            },
            {
                id: 'replicate-flux-mcp',
                name: 'Replicate Flux Image Gen',
                description: 'Generate images and vector graphics via Replicate Flux Schnell and Recraft V3 SVG',
                enabled: true,
                alwaysOn: false,
                priority: 3,
                keywords: ['replicate', 'flux', 'image generation', 'generate image', 'ai image', 'text to image', 'svg', 'recraft', 'illustration'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'replicate-flux-mcp'],
            },
            {
                id: 'mcp-fal-ai-image',
                name: 'Fal.ai Image Gen',
                description: 'Text-to-image generation via Fal.ai model ecosystem (Kolors, Recraft-v3, etc.)',
                enabled: true,
                alwaysOn: false,
                priority: 3,
                keywords: ['fal', 'fal.ai', 'image generation', 'text to image', 'kolors', 'recraft', 'ai art', 'generate image'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'mcp-fal-ai-image'],
            },
        ],
        creative: [
            {
                id: 'canva-dev-mcp',
                name: 'Canva Dev MCP',
                description: 'Build Canva apps and integrations — Apps SDK, Connect APIs, UI components, design guidelines',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['canva', 'canva app', 'canva sdk', 'canva plugin', 'canva integration', 'canva design', 'canva template'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@canva/cli', 'mcp'],
            },
            {
                id: 'canva-api-mcp',
                name: 'Canva API MCP',
                description: 'Manage Canva designs, brands, assets, and users via Canva API',
                enabled: true,
                alwaysOn: false,
                priority: 2,
                keywords: ['canva api', 'canva design', 'canva brand', 'canva asset', 'canva export', 'canva template', 'social media design'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@iflow-mcp/mattcoatsworth-canva-mcp-server'],
            },
            {
                id: 'adobe-creative-suite-mcp',
                name: 'Adobe Creative Suite MCP',
                description: 'AI-powered automation for Photoshop, Premiere Pro, Illustrator, and InDesign',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['adobe', 'photoshop', 'premiere', 'illustrator', 'indesign', 'creative cloud', 'psd', 'ai file', 'after effects', 'creative suite'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'adobe-mcp-servers'],
            },
        ],
        video: [
            {
                id: 'runway-api-mcp',
                name: 'Runway Gen-4 MCP',
                description: 'Generative video via Runway Gen-4 and Aleph models — text/image to video, motion generation',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['runway', 'gen-4', 'video generation', 'text to video', 'image to video', 'motion', 'generative video', 'aleph', 'ai video'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@anthropic-ai/runway-mcp-server'],
            },
            {
                id: 'ffmpeg-mcp',
                name: 'FFmpeg Video/Audio MCP',
                description: 'Video and audio editing via FFmpeg — trim, merge, convert, resize, effects, audio extraction, overlays',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['ffmpeg', 'video edit', 'audio edit', 'transcode', 'convert video', 'trim video', 'merge video', 'video effects', 'audio extract', 'overlay', 'watermark', 'subtitle'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'ffmpeg-mcp-comprehensive'],
            },
            {
                id: 'premiere-pro-mcp',
                name: 'Adobe Premiere Pro MCP',
                description: 'Automate Premiere Pro — markers, metadata, export, timeline operations',
                enabled: true,
                alwaysOn: false,
                priority: 2,
                keywords: ['premiere pro', 'video editing', 'timeline', 'markers', 'export video', 'adobe premiere', 'nle', 'video production'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'premiere-pro-mcp'],
            },
        ],
        three_d: [
            {
                id: 'blender-mcp',
                name: 'Blender MCP',
                description: 'Control Blender in real-time — 3D modeling, scene creation, rendering via natural language',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['blender', '3d', 'modeling', 'render', 'scene', 'mesh', 'material', 'texture', 'animation', '3d model', 'sculpt', 'cycles', 'eevee'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@anthropic-ai/blender-mcp-server'],
            },
        ],
        stock: [
            {
                id: 'cloudinary-mcp',
                name: 'Cloudinary Media MCP',
                description: 'Upload, transform, optimize, and manage media assets via Cloudinary',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['cloudinary', 'media management', 'image transform', 'optimize image', 'upload media', 'cdn', 'media asset', 'resize image', 'crop image'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@cloudinary/mcp-server'],
            },
            {
                id: 'unsplash-mcp',
                name: 'Unsplash Stock Photos MCP',
                description: 'Search and fetch high-quality stock photos from Unsplash',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['unsplash', 'stock photo', 'free photo', 'stock image', 'photo search', 'creative commons', 'photography', 'hero image', 'background image'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'unsplash-mcp'],
            },
        ],
        typography: [
            {
                id: 'google-fonts-mcp',
                name: 'Google Fonts MCP',
                description: 'Search, preview, and integrate Google Fonts — font discovery, pairing, and CSS generation',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['font', 'fonts', 'google fonts', 'typography', 'typeface', 'font family', 'font weight', 'font pairing', 'serif', 'sans-serif', 'monospace', 'display font', 'web font'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'google-fonts-mcp'],
            },
        ],
        firebase: [
            {
                id: 'firebase-mcp-server',
                name: 'Firebase MCP',
                description: 'Manage Firebase projects, apps, and services',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['firebase', 'hosting', 'firebase app', 'firebase project', 'auth', 'authentication', 'storage rules', 'security rules', 'functions'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'firebase-mcp'],
            },
        ],
        search: [
        ],
        maps: [
            {
                id: 'gmp-code-assist',
                name: 'Google Maps Platform Code Assist',
                description: 'Google Maps Platform documentation and code assistance',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['maps', 'google maps', 'places', 'geocoding', 'routing', 'location', 'geospatial', 'address', 'latitude', 'longitude', 'gmp'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'gmp-mcp'],
            },
        ],
        knowledge: [
            {
                id: 'developer-knowledge-mcp',
                name: 'Developer Knowledge MCP',
                description: 'Search Google developer documentation',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['documentation', 'docs', 'api reference', 'google cloud docs', 'firebase docs', 'android', 'chrome', 'tensorflow'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'developer-knowledge-mcp'],
            },
        ],
        reasoning: [
            {
                id: 'sequential-thinking',
                name: 'Sequential Thinking',
                description: 'Step-by-step reasoning for complex problems',
                enabled: true,
                alwaysOn: false,
                priority: 1,
                keywords: ['think', 'reason', 'plan', 'analyze', 'problem solving', 'step by step', 'breakdown', 'sequential', 'complex problem'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', 'sequential-thinking-mcp'],
            },
        ],
        browser: [
            {
                id: 'playwright-mcp',
                name: 'Playwright MCP',
                description: 'Official Playwright MCP Server for dynamic, agentic browser automation',
                enabled: true,
                alwaysOn: false,
                priority: 2,
                keywords: ['browser', 'browse', 'playwright', 'navigate', 'click', 'screenshot', 'scrape', 'interact'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@modelcontextprotocol/server-playwright'],
            },
        ],
        utilities: [
            {
                id: 'home-assistant-mcp',
                name: 'Home Assistant MCP',
                description: 'Official Home Assistant MCP Server for smart home device discovery, status queries, and commands',
                enabled: true,
                alwaysOn: false,
                priority: 2,
                keywords: ['home assistant', 'home', 'assistant', 'hass', 'device', 'switch', 'light', 'sensor', 'climate', 'smart home', 'automation', 'trigger', 'command'],
                transport: 'stdio',
                command: 'npx',
                args: ['-y', '@modelcontextprotocol/server-homeassistant'],
                env: {
                    HOMEASSISTANT_URL: '${HASS_URL}',
                    HOMEASSISTANT_API_TOKEN: '${HASS_TOKEN}',
                },
            },
        ],
    },
} as const satisfies CapabilityManifest;
