/**
 * Static Compiled Knowledge Layer
 * Dynamically generated by StaticESMCompiler. Tree-shakable, sub-millisecond local cache.
 */
export const staticKnowledgeIndex = {
    "agent_excellence_2026": {
        "filename": "AGENT_EXCELLENCE_2026.md",
        "title": "AGENT_EXCELLENCE_2026",
        "tags": [],
        "summary": "Agent Excellence 2026    This document captures research-backed upgrades for V6 agents, skills, and orchestration.       Applied Principles    - **Trajectory-level evals** over output-only scoring.  - **Trace-first observability** with run-level diagnostics.  - **Tool contract discipline** (`ok/da...",
        "compiledAt": "2026-05-28T14:11:40.449Z"
    },
    "agent_structural_audit": {
        "filename": "AGENT_STRUCTURAL_AUDIT.md",
        "title": "AGENT_STRUCTURAL_AUDIT",
        "tags": [],
        "summary": "Agent Structural Integrity Audit — V6  > **Source Signal**: IE-IDX-0121 + IE-IDX-0118 (Flipboard Sentinel, May 4 2026) > **Thesis**: \"The state machine, the assignee field, the audit history, the dependency graph — those are staying. They are quietly becoming the most strategic infrastructure in t...",
        "compiledAt": "2026-05-28T14:11:40.450Z"
    },
    "context_efficiency_protocol": {
        "filename": "CONTEXT_EFFICIENCY_PROTOCOL.md",
        "title": "CONTEXT_EFFICIENCY_PROTOCOL",
        "tags": [],
        "summary": "Context Efficiency Protocol (CEP)    > **V6 Governance Document** — Binding on all agent sessions.  > Precedence: Equal to ROUTING_CONTRACT.md in the governance stack.    ---       Problem Statement    Design-heavy projects (Luminous Gallery, Barnstorm Deck, Sentinel Command, World Compiler) repea...",
        "compiledAt": "2026-05-28T14:11:40.451Z"
    },
    "design": {
        "filename": "DESIGN.md",
        "title": "DESIGN",
        "tags": [],
        "summary": "Creative Liberation Engine — Visual DESIGN.md    > **ATELIER & SENTINEL SOURCE OF TRUTH**  > This file is the sovereign, machine-readable UI blueprint for the Creative Liberation Engine.  > It aggregates all thematic CSS tokens, Tailwind v4 configurations, and structural guidelines.  > Any agent (e.g., ATELIER) gener...",
        "compiledAt": "2026-05-28T14:11:40.451Z"
    },
    "dynamic_routing_architecture": {
        "filename": "DYNAMIC_ROUTING_ARCHITECTURE.md",
        "title": "DYNAMIC_ROUTING_ARCHITECTURE",
        "tags": [],
        "summary": "Creative Liberation Engine: Dynamic Routing & Meta-Orchestration Architecture  **Status:** Active Codification **Stance:** INFRASTRUCTURE & ORCHESTRATOR **Objective:** Evolve Creative Liberation Engine from a reactive conversational tool into a proactive, self-modifying, sovereign creative OS.     1. The Core Paradig...",
        "compiledAt": "2026-05-28T14:11:40.451Z"
    },
    "filesystem_policy": {
        "filename": "FILESYSTEM_POLICY.md",
        "title": "FILESYSTEM_POLICY",
        "tags": [],
        "summary": "V6 Filesystem Policy       Purpose    Define where code, generated artifacts, archives, and migrations are allowed to live in V6. This policy prevents scatter — every file has exactly one canonical home.       Directory Taxonomy        Active Code    | Directory | Purpose | Ownership | Contents |...",
        "compiledAt": "2026-05-28T14:11:40.451Z"
    },
    "glasses_paired_walkthrough": {
        "filename": "GLASSES_PAIRED_WALKTHROUGH.md",
        "title": "GLASSES_PAIRED_WALKTHROUGH",
        "tags": [],
        "summary": "🎉 Walkthrough: Physical Glasses Pairing Established!    Creative Liberation Engine V6 Spatial & Acoustic Integration  > **Author:** AVERI (ATHENA / VERA / IRIS)   > **Stance:** INFRASTRUCTURE / DEVOPS | **Status:** 100% PAIRED & ACTIVE   > **Walkthrough Path:** [GLASSES_PAIRED_WALKTHROUGH.md](file:///y:/br...",
        "compiledAt": "2026-05-28T14:11:40.452Z"
    },
    "governance_precedence": {
        "filename": "GOVERNANCE_PRECEDENCE.md",
        "title": "GOVERNANCE_PRECEDENCE",
        "tags": [],
        "summary": "V6 Governance Precedence       Purpose    Reconcile governance conflicts between V6 and prior versions. Establish clear authority so that no ambiguity exists about which rules govern V6 behavior.       Sovereignty Declaration    **V6 is a sovereign build root.** It is not a branch, fork, or subdir...",
        "compiledAt": "2026-05-28T14:11:40.452Z"
    },
    "gpu_growth_plan": {
        "filename": "GPU_GROWTH_PLAN.md",
        "title": "GPU_GROWTH_PLAN",
        "tags": [],
        "summary": "GPU Growth Plan — Creative Liberation Engine V6    > **Version:** 1.0.0    > **Source:** Article  12 — Kimi K2.6, Article  6 — MultiWorld, Article  8 — OpenCode    > **Date:** 2026-04-22    ---       Current Hardware Profile    | Component | Spec | Capacity |  |-----------|------|----------|  | **GPU** | NV...",
        "compiledAt": "2026-05-28T14:11:40.452Z"
    },
    "hardening_helices": {
        "filename": "HARDENING_HELICES.md",
        "title": "HARDENING_HELICES",
        "tags": [],
        "summary": "V6 Hardening Helices    This document defines the six parallel hardening lanes that must remain in a hardened state before final live connectivity and operations testing.       Helix A: Execution Plane    - Dispatch contract integrity  - Idempotency guarantees  - Retry and backpressure controls  -...",
        "compiledAt": "2026-05-28T14:11:40.452Z"
    },
    "ideation_agenda_2026q2": {
        "filename": "IDEATION_AGENDA_2026Q2.md",
        "title": "IDEATION_AGENDA_2026Q2",
        "tags": [],
        "summary": "🧠 IDEATION Agenda — Creative Liberation Engine V6 Evolution    > **Date:** 2026-04-30  > **Phase:** Post-Phase 7 (SHIP) — All foundation phases complete  > **Source:** Gemini brainstorm sessions (9 conversations) + V6 codebase audit  > **Protocol:** IDEATE → route to PLAN (infrastructure) or DESIGN (produc...",
        "compiledAt": "2026-05-28T14:11:40.452Z"
    },
    "ideation_lifecycle": {
        "filename": "IDEATION_LIFECYCLE.md",
        "title": "IDEATION_LIFECYCLE",
        "tags": [],
        "summary": "Ideation Lifecycle System  > **Status:** Contracted   > **Schema:** `schemas/IDEATION_LIFECYCLE.schema.json`, `schemas/IDEATION_REGISTRY.schema.json`   > **Owner:** ATHENA (strategic), Flipboard Sentinel (ingestion), Sentinel Command (UI)   > **Phase:** WS-02 → WS-03  ---     Problem Statement  Id...",
        "compiledAt": "2026-05-28T14:11:40.452Z"
    },
    "intent_routing_contract": {
        "filename": "INTENT_ROUTING_CONTRACT.md",
        "title": "INTENT_ROUTING_CONTRACT",
        "tags": [],
        "summary": "INTENT_ROUTING_CONTRACT.md — Creative Liberation Engine V6  > **Version:** 1.0.0   > **Status:** ACTIVE   > **Owner:** AVERI Collective (ATHENA · VERA · IRIS)   > **Governance:** `docs/GOVERNANCE_PRECEDENCE.md` — Layer 3   > **Last Updated:** 2026-05-22  ---     1. Purpose  This contract defines how natural...",
        "compiledAt": "2026-05-28T14:11:40.453Z"
    },
    "kroma_space_blueprint": {
        "filename": "KROMA_SPACE_BLUEPRINT.md",
        "title": "KROMA_SPACE_BLUEPRINT",
        "tags": [],
        "summary": "> WARNING DEPRECATED - Consolidated into NEXUS. See docs/NEXUS.md    KROMA.space: Product Specification & Architecture Blueprint       1. Executive Summary  **Project Name:** KROMA.space  **Vision:** An \"operating system for digital art.\" KROMA transforms static 2D portfolios and images into living,...",
        "compiledAt": "2026-05-28T14:11:40.453Z"
    },
    "long_horizon_dispatch": {
        "filename": "LONG_HORIZON_DISPATCH.md",
        "title": "LONG_HORIZON_DISPATCH",
        "tags": [],
        "summary": "Long-Horizon Dispatch — Extension Specification    > **Version:** 1.0.0    > **Source:** Article  12 — \"Kimi K2.6 Runs Agents for Days\" (VentureBeat, Apr 2026)    > **Date:** 2026-04-22    ---       Problem Statement    V6's dispatch architecture currently handles **task-level execution** — indivi...",
        "compiledAt": "2026-05-28T14:11:40.454Z"
    },
    "memory_spine": {
        "filename": "MEMORY_SPINE.md",
        "title": "MEMORY_SPINE",
        "tags": [],
        "summary": "V6 Memory Spine       Purpose    Define how V6 handles durable memory across all providers using a single canonical contract. The memory spine is the nervous system of Creative Liberation Engine — every decision, pattern, session, and artifact flows through it.       Canonical Unit    - **Schema**: `schemas...",
        "compiledAt": "2026-05-28T14:11:40.454Z"
    },
    "migration_plan": {
        "filename": "MIGRATION_PLAN.md",
        "title": "MIGRATION_PLAN",
        "tags": [],
        "summary": "V6 Migration Plan     Sole-surface doctrine (authoritative)  **V6 alone is canonical.** Heritage migration was how intent and artifacts were **ingested once**; it is not an invitation to keep V1–V5 as co-equal runtimes or ongoing “parity” checks. All forward implementation, deployment, and governa...",
        "compiledAt": "2026-05-28T14:11:40.454Z"
    },
    "migration_readiness": {
        "filename": "MIGRATION_READINESS.md",
        "title": "MIGRATION_READINESS",
        "tags": [],
        "summary": "V6 Migration Readiness       Purpose    Define the acceptance criteria that must be satisfied before any code migration from V1–V5 begins. This document gates the transition from contract architecture (Phases 0–6) to runtime implementation (Phase 7+).       Readiness Checklist    All criteria must...",
        "compiledAt": "2026-05-28T14:11:40.454Z"
    },
    "nas_path_registry": {
        "filename": "NAS_PATH_REGISTRY.md",
        "title": "NAS_PATH_REGISTRY",
        "tags": [],
        "summary": "NAS Path Registry (Creative Liberation Engine V6)  This registry defines canonical NAS roots to prevent path drift and cross-domain writes.     Canonical Roots  - `vault_root`: `\\\\127.0.0.1\\The Vault` - `engine_root`: `\\\\127.0.0.1\\The Vault\\Creative Liberation Engine` - `engine_telemetry_root`: `\\\\127.0.0.1\\...",
        "compiledAt": "2026-05-28T14:11:40.454Z"
    },
    "nexus": {
        "filename": "NEXUS.md",
        "title": "NEXUS",
        "tags": [],
        "summary": "NEXUS — Sovereign Unified Surface  > **Status:** IN_PROGRESS   > **ID:** IE-HRT-052   > **Version:** 3.0   > **Supersedes:** KROMA_SPACE_BLUEPRINT.md, SOVEREIGN_IDE.md, Kade IDE (IE-HRT-038)   > **Last Updated:** 2026-05-15  ---     Definition  NEXUS is the **master sovereign surface** for the Inc...",
        "compiledAt": "2026-05-28T14:11:40.454Z"
    },
    "nexus_spatial_segmenter_blueprint": {
        "filename": "NEXUS_SPATIAL_SEGMENTER_BLUEPRINT.md",
        "title": "NEXUS_SPATIAL_SEGMENTER_BLUEPRINT",
        "tags": [],
        "summary": "MASTER ARCHITECTURAL BLUEPRINT    System: NEXUS Real-Time Spatial Segmenter & Node-Graph Animation Engine (IE-HRT-080) **Version:** 1.0.0   **Status:** PROPOSED / PLAN   **Lead Architects:** ATHENA (Creative Director), VERA (Quality Control), IRIS (Systems Integrator)   **Target Root:** `services/...",
        "compiledAt": "2026-05-28T14:11:40.454Z"
    },
    "roadmap": {
        "filename": "ROADMAP.md",
        "title": "ROADMAP",
        "tags": [],
        "summary": "Creative Liberation Engine V6 System Roadmap (Historical & Active Milestones)    This document tracks the macro-level system integration phases of the clean-root Creative Liberation Engine V6 codebase. It acts as an architectural ledger and does not represent individual conversational task workflows (which are tracked via task.md or HANDOFF.md).",
        "compiledAt": "2026-06-02T19:26:00.000Z"
    },
    "qdrant_vs_chromadb_evaluation": {
        "filename": "QDRANT_VS_CHROMADB_EVALUATION.md",
        "title": "QDRANT_VS_CHROMADB_EVALUATION",
        "tags": [],
        "summary": "📊 Qdrant vs. ChromaDB Architectural Evaluation    B2B Sovereign Vector Memory Spine & Spatial Takeoff (Creative Liberation Engine V6)  > **Date:** 2026-05-26 > **Strategic Focus:** Local-first, self-hostable, low-resource spatial indexing for commercial ConTech operations.  ---     1. Executive Summary  As...",
        "compiledAt": "2026-05-28T14:11:40.455Z"
    },
    "rayban_meta_setup_guide": {
        "filename": "RAYBAN_META_SETUP_GUIDE.md",
        "title": "RAYBAN_META_SETUP_GUIDE",
        "tags": [],
        "summary": "🕶️ Setup Guide: Connecting Ray-Ban Meta Smart Glasses    Creative Liberation Engine V6 Spatial Activation Checklist  > **Author:** AVERI (ATHENA / VERA / IRIS)   > **Stance:** INFRASTRUCTURE / DEVOPS | **Priority:** Critical   > **Target Document:** [RAYBAN_META_SETUP_GUIDE.md](file:///y:/creative-liberation-engine/doc...",
        "compiledAt": "2026-05-28T14:11:40.455Z"
    },
    "rayban_meta_strategic_brief": {
        "filename": "RAYBAN_META_STRATEGIC_BRIEF.md",
        "title": "RAYBAN_META_STRATEGIC_BRIEF",
        "tags": [],
        "summary": "🕶️ Strategic Brief: Ray-Ban Meta Wearables Integration    Creative Liberation Engine V6 Strategy — Q2 2026  > **Author:** AVERI (ATHENA / VERA / IRIS)   > **Route:** STRATEGIC | **Priority:** High   > **Target Document:** [RAYBAN_META_STRATEGIC_BRIEF.md](file:///y:/creative-liberation-engine/docs/RAYBAN_META_STRATEGIC_...",
        "compiledAt": "2026-05-28T14:11:40.455Z"
    },
    "rayban_meta_usb_debugging": {
        "filename": "RAYBAN_META_USB_DEBUGGING.md",
        "title": "RAYBAN_META_USB_DEBUGGING",
        "tags": [],
        "summary": "🔌 Developer Guide: Direct USB (ADB) & Bluetooth Integration    Ray-Ban Meta Hardware Debugging & Local Compute Routing  > **Author:** AVERI (ATHENA / VERA / IRIS)   > **Stance:** INFRASTRUCTURE / DEVOPS | **Priority:** High   > **Target Document:** [RAYBAN_META_USB_DEBUGGING.md](file:///y:/brainc...",
        "compiledAt": "2026-05-28T14:11:40.455Z"
    },
    "readme": {
        "filename": "README.md",
        "title": "README",
        "tags": [],
        "summary": "V6 Docs Index    This directory contains the human-readable contracts and planning canon for V6.       Core Documents    - `SYSTEM_CONTRACT.md` - structural rules for V6  - `ROADMAP.md` - macro system integration milestones and roadmap  - `MEMORY_SPINE.md` - canonical memory model and providers  - `ROUTING...",
        "compiledAt": "2026-06-02T19:26:00.000Z"
    },
    "routing_contract": {
        "filename": "ROUTING_CONTRACT.md",
        "title": "ROUTING_CONTRACT",
        "tags": [],
        "summary": "V6 Routing Contract       Purpose    Define how HTTP and internal routes are declared, owned, and validated in V6. Every route in the system must be declared in a manifest before code, gateway configs, or reverse proxy rules can reference it.       Canonical Units    | Schema | Purpose |  |---|---...",
        "compiledAt": "2026-05-28T14:11:40.455Z"
    },
    "skill_target_matrix": {
        "filename": "SKILL_TARGET_MATRIX.md",
        "title": "SKILL_TARGET_MATRIX",
        "tags": [],
        "summary": "V6 Skill Target Matrix (Batch-35)    This defines the first expansion batch for V6 skill coverage before workflow canonicalization.    Rule: 7 families x top 5 skills each = 35 total.       1) Runtime Ops (5)    | Skill ID | Owner Hive | Priority | Purpose |  |---|---|---|---|  | `service-health-t...",
        "compiledAt": "2026-05-28T14:11:40.455Z"
    },
    "skill_target_matrix_batch2": {
        "filename": "SKILL_TARGET_MATRIX_BATCH2.md",
        "title": "SKILL_TARGET_MATRIX_BATCH2",
        "tags": [],
        "summary": "V6 Skill Target Matrix (Batch-35-B2)    Second expansion batch for V6 skill coverage.    Rule: 7 families x top 5 skills each = 35 total.       1) Runtime Ops (5)    | Skill ID | Owner Hive | Priority | Purpose |  |---|---|---|---|  | `runtime-chaos-drill` | `systems` | P0 | Run controlled chaos d...",
        "compiledAt": "2026-05-28T14:11:40.457Z"
    },
    "sovereign_contech_integration_plan": {
        "filename": "SOVEREIGN_CONTECH_INTEGRATION_PLAN.md",
        "title": "SOVEREIGN_CONTECH_INTEGRATION_PLAN",
        "tags": [],
        "summary": "🏗️ Sovereign ConTech Operations — B2B Vertical Integration Plan    B2B Service Platform & Workflow Compression (Creative Liberation Engine V6)  > **Date:** 2026-05-26 > **Strategic Intent:** Build a sovereign, local-first B2B service platform for commercial construction managers, estimators, and B2B develo...",
        "compiledAt": "2026-05-28T14:11:40.457Z"
    },
    "sovereign_ide": {
        "filename": "SOVEREIGN_IDE.md",
        "title": "SOVEREIGN_IDE",
        "tags": [],
        "summary": "> WARNING DEPRECATED - Consolidated into NEXUS. See docs/NEXUS.md    Sovereign IDE Integration — Continue.dev    > **Version:** 1.0.0    > **Date:** 2026-04-22    > **Context:** Integration of zero-latency, sovereign autocomplete and codebase reasoning via Continue.dev, mapping directly to the V6 mo...",
        "compiledAt": "2026-05-28T14:11:40.457Z"
    },
    "spatial_bridge_walkthrough": {
        "filename": "SPATIAL_BRIDGE_WALKTHROUGH.md",
        "title": "SPATIAL_BRIDGE_WALKTHROUGH",
        "tags": [],
        "summary": "🕶️ Walkthrough: Universal Spatial Bridge Validation    Creative Liberation Engine V6 Spatial & Computer Vision Validation  > **Author:** AVERI (ATHENA / VERA / IRIS)   > **Stance:** INFRASTRUCTURE / SYSTEM ARCHITECTS | **Status:** 100% SHIPPED & VALIDATED   > **Walkthrough Path:** [SPATIAL_BRIDGE_WALKTHROU...",
        "compiledAt": "2026-05-28T14:11:40.457Z"
    },
    "strategic_thesis": {
        "filename": "STRATEGIC_THESIS.md",
        "title": "STRATEGIC_THESIS",
        "tags": [],
        "summary": "Strategic Thesis — Creative Liberation Engine V6    > **Version:** 1.0.0    > **Source:** Article  9 — \"Why World Models Will Become a Platform Capability\" (Fast Company, Feb 2026)    > **Author:** AVERI Collective    > **Date:** 2026-04-22    ---       Core Thesis    **CLE doesn't compete on model ca...",
        "compiledAt": "2026-05-28T14:11:40.457Z"
    },
    "system_contract": {
        "filename": "SYSTEM_CONTRACT.md",
        "title": "SYSTEM_CONTRACT",
        "tags": [],
        "summary": "V6 System Contract       Purpose    This document defines the non-negotiable structural rules for Creative Liberation Engine V6.       Core Rules    1. `creative-liberation-engine` is a sovereign build root, not a subfolder of prior versions.  2. V5 is reference-only during V6 preparation.  3. Every durable capability m...",
        "compiledAt": "2026-05-28T14:11:40.457Z"
    },
    "v5_sunset": {
        "filename": "V5_SUNSET.md",
        "title": "V5_SUNSET",
        "tags": [],
        "summary": "⚠️ BRAINCHILD V5 — ARCHIVED & PURGED  **Sunset Date**: 2026-04-21T14:10:00-04:00 **Purge Date**: 2026-05-11 **Successor**: creative-liberation-engine     Status: ARCHIVED & DECOUPLED ❌  V5 core services have been decommissioned and all physical directory structures have been purged from the active NAS environm...",
        "compiledAt": "2026-05-28T14:11:40.457Z"
    },
    "v6_constitution": {
        "filename": "V6_CONSTITUTION.md",
        "title": "V6_CONSTITUTION",
        "tags": [],
        "summary": "Creative Liberation Engine V6 Constitution  > **Version:** 6.0.0   > **Status:** RATIFIED & ACTIVE   > **Owner:** AVERI Collective (ATHENA · VERA · IRIS)   > **Target Root:** `creative-liberation-engine`   > **Enforced by:** `docs/SYSTEM_CONTRACT.md`, `docs/GOVERNANCE_PRECEDENCE.md`, `tools/validate-contracts.mjs`, `run...",
        "compiledAt": "2026-05-28T14:11:40.457Z"
    },
    "v6_parity_matrix": {
        "filename": "V6_PARITY_MATRIX.md",
        "title": "V6_PARITY_MATRIX",
        "tags": [],
        "summary": "V6 Capability Catalog (Sole Surface)  **Doctrine:** Creative Liberation Engine V6 is the **only** active capability surface. Every shipped capability lives here under V6 contracts, routes, and registries. V1–V5 exist **only** as read-only heritage (intent, archaeology, legal context)—not as parallel systems...",
        "compiledAt": "2026-05-28T14:11:40.458Z"
    },
    "value_metrics": {
        "filename": "VALUE_METRICS.md",
        "title": "VALUE_METRICS",
        "tags": [],
        "summary": "Value Metrics Framework — Creative Liberation Engine V6    > **Version:** 1.0.0    > **Sources:** Article  13 (Fortune, \"Hidden ROI of AI\"), Article  9 (Fast Company), Article  10 (Fast Company)    > **Date:** 2026-04-22    ---       Why Traditional ROI Metrics Miss the Point    From Deloitte's \"2026 State...",
        "compiledAt": "2026-05-28T14:11:40.458Z"
    },
    "weave_video_conductor": {
        "filename": "WEAVE_VIDEO_CONDUCTOR.md",
        "title": "WEAVE_VIDEO_CONDUCTOR",
        "tags": [],
        "summary": "Figma Weave Multi-Modal Video Conductor  > **Status:** SHIPPED (V6 Helix Extension)   > **ID:** IE-HRT-082   > **Version:** 1.0.0   > **Location:** [VideoConductorPanel.jsx](file:///y:/creative-liberation-engine/apps/nexus/src/panels/VideoConductorPanel.jsx)   > **AST Layout Schema:** [video-conductor.ast.json...",
        "compiledAt": "2026-05-28T14:11:40.458Z"
    },
    "workflows_enrichment": {
        "filename": "WORKFLOWS_ENRICHMENT.md",
        "title": "WORKFLOWS_ENRICHMENT",
        "tags": [],
        "summary": "WORKFLOWS_ENRICHMENT.md — Design Document  > **Version:** 1.0.0   > **Status:** DESIGN   > **Owner:** AVERI Collective (ATHENA · VERA · IRIS)   > **Depends on:** `docs/INTENT_ROUTING_CONTRACT.md`, `runtime/registry/workflows.canonical.json`   > **Last Updated:** 2026-05-22  ---     1. Purpose  Thi...",
        "compiledAt": "2026-05-28T14:11:40.458Z"
    },
    "workflow_target_matrix": {
        "filename": "WORKFLOW_TARGET_MATRIX.md",
        "title": "WORKFLOW_TARGET_MATRIX",
        "tags": [],
        "summary": "V6 Workflow Target Matrix    Canonical workflow set required for V6 orchestration reliability.       Core Spine (Mandatory)    | Workflow ID | Purpose |  |---|---|  | `ideate` | Discovery and direction generation |  | `plan` | Architecture and execution planning |  | `ship` | Implementation and de...",
        "compiledAt": "2026-05-28T14:11:40.458Z"
    },
    "barnstorm_vlan_topology": {
        "filename": "barnstorm_vlan_topology.md",
        "title": "barnstorm_vlan_topology",
        "tags": [],
        "summary": "Sovereign Compute Farm: VLAN Topology & Architecture       Objective  To establish a strict network topology for The Barnstorm's Sovereign Compute Farm that guarantees absolute client data sanctity while safely enabling shared compute pooling for the studio's internal operations.       Core Tenets...",
        "compiledAt": "2026-05-28T14:11:40.458Z"
    }
};
export function lookupStaticKnowledge(key) {
    return staticKnowledgeIndex[key.toLowerCase()];
}
export function searchStaticKnowledge(query) {
    const q = query.toLowerCase();
    return Object.values(staticKnowledgeIndex).filter(item => item.title.toLowerCase().includes(q) ||
        item.summary.toLowerCase().includes(q) ||
        item.tags.some(t => t.toLowerCase().includes(q)));
}
