/**
 * Static Compiled Knowledge Layer
 * Dynamically generated by StaticESMCompiler. Tree-shakable, sub-millisecond local cache.
 */
export interface CompiledKnowledgeItem {
    filename: string;
    title: string;
    tags: string[];
    summary: string;
    compiledAt: string;
}
export declare const staticKnowledgeIndex: Record<string, CompiledKnowledgeItem>;
export declare function lookupStaticKnowledge(key: string): CompiledKnowledgeItem | undefined;
export declare function searchStaticKnowledge(query: string): CompiledKnowledgeItem[];
