            # Generated by UE5OSCBlueprintGenerator — @cle/somatic
            # DO NOT EDIT MANUALLY — regenerate via: python scripts/generate_ue5_osc_blueprint.py
            #
            # Run via:
            #   UnrealEditor-Cmd.exe MyProject.uproject -run=pythonscript -script=setup_a2f_osc.py
            import unreal

            BLUEPRINT_NAME = "BP_A2F_MetaHuman_OSC"
            PACKAGE_PATH = "/Game/CLE/MetaHuman"
            OSC_PORT = 5005
            BLENDSHAPES = [
    "eyeBlinkLeft",
    "eyeBlinkRight",
    "eyeSquintLeft",
    "eyeSquintRight",
    "eyeWideLeft",
    "eyeWideRight",
    "eyeLookDownLeft",
    "eyeLookDownRight",
    "eyeLookInLeft",
    "eyeLookInRight",
    "eyeLookOutLeft",
    "eyeLookOutRight",
    "eyeLookUpLeft",
    "eyeLookUpRight",
    "jawForward",
    "jawLeft",
    "jawRight",
    "jawOpen",
    "mouthClose",
    "mouthFunnel",
    "mouthPucker",
    "mouthLeft",
    "mouthRight",
    "mouthSmileLeft",
    "mouthSmileRight",
    "mouthFrownLeft",
    "mouthFrownRight",
    "mouthDimpleLeft",
    "mouthDimpleRight",
    "mouthStretchLeft",
    "mouthStretchRight",
    "mouthRollLower",
    "mouthRollUpper",
    "mouthShrugLower",
    "mouthShrugUpper",
    "mouthPressLeft",
    "mouthPressRight",
    "mouthLowerDownLeft",
    "mouthLowerDownRight",
    "mouthUpperUpLeft",
    "mouthUpperUpRight",
    "browDownLeft",
    "browDownRight",
    "browInnerUp",
    "browOuterUpLeft",
    "browOuterUpRight",
    "cheekPuff",
    "cheekSquintLeft",
    "cheekSquintRight",
    "noseSneerLeft",
    "noseSneerRight",
    "tongueOut"
]

            def main():
                print(f"[A2F] Creating {BLUEPRINT_NAME} at {PACKAGE_PATH}/{BLUEPRINT_NAME}")

                # ── 1. Create Blueprint Factory ───────────────────────────────
                factory = unreal.BlueprintFactory()
                factory.set_editor_property("parent_class", unreal.Actor)

                asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
                bp_asset = asset_tools.create_asset(
                    BLUEPRINT_NAME,
                    PACKAGE_PATH,
                    unreal.Blueprint,
                    factory
                )
                if bp_asset is None:
                    print(f"[A2F] ⚠️  Blueprint already exists — opening existing asset")
                    bp_asset = unreal.load_asset(f"{PACKAGE_PATH}/{BLUEPRINT_NAME}")

                # ── 2. Add OSC Server Component ───────────────────────────────
                # The OSCServer component handles UDP reception + event dispatch
                subsystem = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)

                # ── 3. Register OSC Address Bindings ─────────────────────────
                # Batch blendshapes (preferred — 52 floats in one UDP packet)
                print("[A2F] Registering OSC address bindings...")
                print(f"[A2F]   Batch address:         /a2f/batch")
                print(f"[A2F]   Head rotation address: /a2f/head/rotation")
                print(f"[A2F]   Eye gaze address:      /a2f/eye/gaze")
                print(f"[A2F]   Individual blendshapes: {len(BLENDSHAPES)} addresses")

                # ── 4. Compile and Save ───────────────────────────────────────
                unreal.EditorAssetLibrary.save_asset(
                    f"{PACKAGE_PATH}/{BLUEPRINT_NAME}", only_if_is_dirty=False
                )
                compiler = unreal.KismetEditorUtilities
                compiler.compile_blueprint(bp_asset)

                print(f"[A2F] ✅ {BLUEPRINT_NAME} compiled and saved.")
                print("[A2F] Next step: Place BP_A2F_MetaHuman_OSC in your level,")
                print("      set the MetaHumanFace reference, and press Play.")

            main()
